// Projects from the parallaxx-git GitHub account, captured on 2026-09-14 from its
// repositories page (primary language only). Refresh with scripts/fetch-work.mjs
// using a token that can see the repositories, then commit the result.
window.PORTFOLIO_WORK = {
  "generatedAt": "2026-09-14T06:40:00Z",
  "owner": {
    "login": "parallaxx-git",
    "label": "Parallaxx",
    "url": "https://github.com/parallaxx-git"
  },
  "repos": [
    { "name": "agentic-dashboard", "description": "Parallaxx Agent Command Center — Web dashboard for managing Claude Code agentic workflows", "url": "https://github.com/parallaxx-git/agentic-dashboard", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-09-14T06:15:55Z", "topics": [] },
    { "name": "shepherd-sandbox", "description": "", "url": "https://github.com/parallaxx-git/shepherd-sandbox", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-09-14T05:27:25Z", "topics": [] },
    { "name": "skill-builder", "description": "Skill Builder — guided wizard that turns a Parallaxx employee's Azure AD profile and answers into ready-to-use AI agent/skill definitions for Claude, ChatGPT, Gemini, and Copilot.", "url": "https://github.com/parallaxx-git/skill-builder", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-09-14T02:40:44Z", "topics": [] },
    { "name": "risk-engine-database", "description": "", "url": "https://github.com/parallaxx-git/risk-engine-database", "language": "PHP", "languages": { "PHP": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-09-13T00:21:25Z", "topics": [] },
    { "name": "permanent-road-safety-barrier-designer", "description": "", "url": "https://github.com/parallaxx-git/permanent-road-safety-barrier-designer", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-09-11T00:00:40Z", "topics": [] },
    { "name": "parallaxx-gis", "description": "", "url": "https://github.com/parallaxx-git/parallaxx-gis", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-09-10T07:03:01Z", "topics": [] },
    { "name": "basemap-builder", "description": "Browser-based builder for simplified vector basemaps and infographics for NZ Traffic Management Plans.", "url": "https://github.com/parallaxx-git/basemap-builder", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-09-03T06:01:54Z", "topics": [] },
    { "name": "CEO_Reports", "description": "", "url": "https://github.com/parallaxx-git/CEO_Reports", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-08-09T23:38:08Z", "topics": [] },
    { "name": "scoro-xero-intelligence-platform", "description": "", "url": "https://github.com/parallaxx-git/scoro-xero-intelligence-platform", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": true, "forkedFrom": "L1013229/scoro-xero-intelligence-platform", "archived": false, "createdAt": null, "pushedAt": "2026-06-18T04:02:57Z", "topics": [] },
    { "name": "trace", "description": "TRACE — TTM Risk Assessment & Control Engine (Parallaxx internal tool)", "url": "https://github.com/parallaxx-git/trace", "language": "HTML", "languages": { "HTML": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-06-10T04:46:20Z", "topics": [] },
    { "name": "risk-assessment", "description": "", "url": "https://github.com/parallaxx-git/risk-assessment", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-05-18T04:58:57Z", "topics": [] },
    { "name": "project-nexus", "description": "Parallaxx HRIS — Next.js 16 + Postgres", "url": "https://github.com/parallaxx-git/project-nexus", "language": "TypeScript", "languages": { "TypeScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-05-12T06:36:46Z", "topics": [] },
    { "name": "risk-engine-interface", "description": "", "url": "https://github.com/parallaxx-git/risk-engine-interface", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-05-09T00:14:23Z", "topics": [] },
    { "name": "ttm-lowest-total-risk-calculator", "description": "TTM Lowest Total Risk Calculator — Parallaxx internal tool", "url": "https://github.com/parallaxx-git/ttm-lowest-total-risk-calculator", "language": "TypeScript", "languages": { "TypeScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-04-23T23:03:36Z", "topics": [] },
    { "name": "taper-calculator", "description": "Taper calculator — Parallaxx internal tool", "url": "https://github.com/parallaxx-git/taper-calculator", "language": "TypeScript", "languages": { "TypeScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-04-23T23:02:13Z", "topics": [] },
    { "name": "parallaxx-cad-block-generator", "description": "CAD block generator — automated traffic management plan drawing components", "url": "https://github.com/parallaxx-git/parallaxx-cad-block-generator", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": true, "forkedFrom": "L1013229/parallaxx-cad-block-generator", "archived": false, "createdAt": null, "pushedAt": "2026-03-13T11:23:43Z", "topics": [] },
    { "name": "parallaxx-scoro-mcp", "description": "MCP server connecting Copilot Studio agents to Scoro API for Parallaxx — estimate creation and data queries", "url": "https://github.com/parallaxx-git/parallaxx-scoro-mcp", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": true, "forkedFrom": "L1013229/parallaxx-scoro-mcp", "archived": false, "createdAt": null, "pushedAt": "2026-03-10T12:46:43Z", "topics": [] },
    { "name": "tmp-warehouse", "description": "Structured TMP data platform — transforming 13+ years of Traffic Management Plan records into a queryable, analytically rich data asset", "url": "https://github.com/parallaxx-git/tmp-warehouse", "language": "", "languages": {}, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-03-10T08:54:44Z", "topics": [] },
    { "name": "ttm-taper-calculator", "description": "", "url": "https://github.com/parallaxx-git/ttm-taper-calculator", "language": "TypeScript", "languages": { "TypeScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-02-13T00:39:07Z", "topics": [] },
    { "name": "austroads-ref-calculator", "description": "", "url": "https://github.com/parallaxx-git/austroads-ref-calculator", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-02-13T00:15:07Z", "topics": [] },
    { "name": "roll-ahead-calculator", "description": "", "url": "https://github.com/parallaxx-git/roll-ahead-calculator", "language": "PHP", "languages": { "PHP": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-02-12T05:50:37Z", "topics": [] },
    { "name": "Risk_Interaction_Tool_V2", "description": "", "url": "https://github.com/parallaxx-git/Risk_Interaction_Tool_V2", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-02-12T02:52:03Z", "topics": [] },
    { "name": "risk-interaction-detection-tool", "description": "PARALLAXX AI PROJECT", "url": "https://github.com/parallaxx-git/risk-interaction-detection-tool", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-02-11T06:33:26Z", "topics": [] },
    { "name": "ip-scanner", "description": "", "url": "https://github.com/parallaxx-git/ip-scanner", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-02-10T10:40:10Z", "topics": [] },
    { "name": "Sharepoint_Archiver", "description": "", "url": "https://github.com/parallaxx-git/Sharepoint_Archiver", "language": "Jupyter Notebook", "languages": { "Jupyter Notebook": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-02-06T05:06:51Z", "topics": [] },
    { "name": "rss_feed_filter", "description": "", "url": "https://github.com/parallaxx-git/rss_feed_filter", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-01-13T22:39:31Z", "topics": [] },
    { "name": "pxx_spark", "description": "", "url": "https://github.com/parallaxx-git/pxx_spark", "language": "", "languages": {}, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2026-01-05T00:55:00Z", "topics": [] },
    { "name": "risk-engine", "description": "", "url": "https://github.com/parallaxx-git/risk-engine", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2025-11-02T05:23:31Z", "topics": [] },
    { "name": "ttm-risk-db", "description": "", "url": "https://github.com/parallaxx-git/ttm-risk-db", "language": "", "languages": {}, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2025-08-21T03:58:11Z", "topics": [] },
    { "name": "ttm-risk-interface", "description": "", "url": "https://github.com/parallaxx-git/ttm-risk-interface", "language": "", "languages": {}, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2025-08-21T03:16:15Z", "topics": [] },
    { "name": "big-dataset", "description": "", "url": "https://github.com/parallaxx-git/big-dataset", "language": "JavaScript", "languages": { "JavaScript": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2025-08-01T01:23:40Z", "topics": [] },
    { "name": "video-converter", "description": "", "url": "https://github.com/parallaxx-git/video-converter", "language": "Python", "languages": { "Python": 1 }, "private": true, "fork": false, "forkedFrom": "", "archived": false, "createdAt": null, "pushedAt": "2025-03-24T04:31:30Z", "topics": [] }
  ]
};
