// Generates js/data.js from the GitHub REST API.
// Node 18+ (global fetch), no dependencies.
//
//   node scripts/fetch-data.mjs [--user jrlabanza] [--out js/data.js]
//
// Set GITHUB_TOKEN to raise the API rate limit. The deploy workflow passes the
// repository's built-in token automatically, so the published site always
// carries fresh data.

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const API = 'https://api.github.com';

function arg(name, fallback) {
  const i = process.argv.indexOf(name);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const user = arg('--user', process.env.GH_USER || 'jrlabanza');
const out = resolve(arg('--out', 'js/data.js'));
const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;

const headers = {
  Accept: 'application/vnd.github+json',
  'User-Agent': `${user}-portfolio-builder`,
};
if (token) headers.Authorization = `Bearer ${token}`;

async function get(path) {
  const url = path.startsWith('http') ? path : `${API}${path}`;
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.json();
}

async function getAllRepos() {
  const repos = [];
  for (let page = 1; page <= 10; page += 1) {
    const batch = await get(
      `/users/${user}/repos?type=owner&sort=updated&per_page=100&page=${page}`,
    );
    repos.push(...batch);
    if (batch.length < 100) break;
  }
  return repos;
}

// Small concurrency pool so an unauthenticated run stays polite.
async function mapPool(items, limit, fn) {
  const results = new Array(items.length);
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const i = next;
      next += 1;
      results[i] = await fn(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return results;
}

async function getLanguages(repos) {
  const map = {};
  // Empty repositories have no language data; skip them to save requests.
  const targets = repos.filter((r) => r.size > 0);
  await mapPool(targets, 4, async (r) => {
    try {
      map[r.name] = await get(r.languages_url);
    } catch (err) {
      // Rate limited or transient failure: fall back to the primary language.
      console.warn(`languages: ${r.name}: ${err.message}`);
      map[r.name] = r.language ? { [r.language]: 1 } : {};
    }
  });
  return map;
}

export function buildData(profile, repos, languages) {
  return {
    generatedAt: new Date().toISOString(),
    profile: {
      login: profile.login,
      name: profile.name || profile.login,
      bio: profile.bio || '',
      avatarUrl: profile.avatar_url,
      url: profile.html_url,
      followers: profile.followers,
      following: profile.following,
      publicRepos: profile.public_repos,
      createdAt: profile.created_at,
      company: profile.company || '',
      location: profile.location || '',
      blog: profile.blog || '',
    },
    repos: repos
      .map((r) => ({
        name: r.name,
        description: r.description || '',
        url: r.html_url,
        homepage: r.homepage || '',
        language: r.language || '',
        languages: languages[r.name] || {},
        stars: r.stargazers_count,
        forks: r.forks_count,
        fork: r.fork,
        archived: r.archived,
        size: r.size,
        createdAt: r.created_at,
        pushedAt: r.pushed_at,
        topics: r.topics || [],
      }))
      .sort((a, b) => b.pushedAt.localeCompare(a.pushedAt)),
  };
}

export function serialize(data) {
  return `// Generated by scripts/fetch-data.mjs on ${data.generatedAt}. Do not edit by hand.\n` +
    `window.PORTFOLIO_DATA = ${JSON.stringify(data, null, 2)};\n`;
}

async function main() {
  console.log(`Fetching GitHub data for ${user}${token ? ' (authenticated)' : ''}…`);
  const profile = await get(`/users/${user}`);
  const repos = await getAllRepos();
  const languages = await getLanguages(repos);
  const data = buildData(profile, repos, languages);
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, serialize(data), 'utf8');
  console.log(`Wrote ${out}: ${data.repos.length} repositories.`);
}

const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
