// Generates js/work.js: projects from another GitHub account (private repos
// included) that should appear on the portfolio alongside the public profile.
//
//   node scripts/fetch-work.mjs --owner parallaxx-git [--label Parallaxx] [--out js/work.js]
//
// Needs a token that can see the owner's repositories: set GITHUB_TOKEN, or be
// signed in to the GitHub CLI (the script falls back to `gh auth token`).
// The deploy workflow cannot refresh this file (its token only sees the
// portfolio repository), so re-run this locally whenever the list changes and
// commit the result.

import { execFileSync } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const API = 'https://api.github.com';

function arg(name, fallback) {
  const i = process.argv.indexOf(name);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const owner = arg('--owner', 'parallaxx-git');
const label = arg('--label', 'Parallaxx');
const out = resolve(arg('--out', 'js/work.js'));

function findToken() {
  if (process.env.GITHUB_TOKEN) return process.env.GITHUB_TOKEN;
  if (process.env.GH_TOKEN) return process.env.GH_TOKEN;
  const candidates = ['gh', 'C:\\Program Files\\GitHub CLI\\gh.exe'];
  for (const bin of candidates) {
    try {
      return execFileSync(bin, ['auth', 'token'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
    } catch {
      // try the next candidate
    }
  }
  return '';
}

const token = findToken();
if (!token) {
  console.error('No GitHub token found. Set GITHUB_TOKEN or run `gh auth login` first.');
  process.exit(1);
}

const headers = {
  Accept: 'application/vnd.github+json',
  Authorization: `Bearer ${token}`,
  'User-Agent': `${owner}-portfolio-builder`,
};

async function get(path) {
  const url = path.startsWith('http') ? path : `${API}${path}`;
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.json();
}

// /users/{owner}/repos only lists public repositories, even with a token.
// Repositories the signed-in user can see (including private ones they
// collaborate on) come from /user/repos, filtered to the owner we want.
async function listRepos() {
  const repos = [];
  for (let page = 1; page <= 20; page += 1) {
    const batch = await get(`/user/repos?per_page=100&page=${page}&sort=updated&affiliation=owner,collaborator,organization_member`);
    repos.push(...batch.filter((r) => r.owner && r.owner.login.toLowerCase() === owner.toLowerCase()));
    if (batch.length < 100) break;
  }
  // Public repositories owned by the account are visible either way.
  const pub = await get(`/users/${owner}/repos?per_page=100&type=owner`);
  for (const r of pub) if (!repos.some((x) => x.id === r.id)) repos.push(r);
  return repos;
}

async function main() {
  const repos = await listRepos();
  const withLanguages = await Promise.all(repos.map(async (r) => {
    let languages = {};
    try { languages = r.size > 0 ? await get(r.languages_url) : {}; } catch (err) { console.warn(`languages: ${r.name}: ${err.message}`); }
    return {
      name: r.name,
      description: r.description || '',
      url: r.html_url,
      homepage: r.homepage || '',
      language: r.language || '',
      languages,
      private: r.private,
      fork: r.fork,
      archived: r.archived,
      size: r.size,
      createdAt: r.created_at,
      pushedAt: r.pushed_at,
      topics: r.topics || [],
    };
  }));
  withLanguages.sort((a, b) => b.pushedAt.localeCompare(a.pushedAt));

  const data = {
    generatedAt: new Date().toISOString(),
    owner: { login: owner, label, url: `https://github.com/${owner}` },
    repos: withLanguages,
  };
  await mkdir(dirname(out), { recursive: true });
  await writeFile(
    out,
    `// Generated by scripts/fetch-work.mjs on ${data.generatedAt}. Re-run it to refresh; do not edit by hand.\n` +
      `window.PORTFOLIO_WORK = ${JSON.stringify(data, null, 2)};\n`,
    'utf8',
  );
  console.log(`Wrote ${out}: ${withLanguages.length} repositories from ${owner}` +
    ` (${withLanguages.filter((r) => r.private).length} private).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
